name: Deploy to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Verify build output
      run: |
        echo "Checking build output structure:"
        ls -la .next/
        echo "Standalone directory:"
        ls -la .next/standalone/ || echo "No standalone directory"
        echo "Static directory:"
        ls -la .next/static/ || echo "No static directory"

    - name: Prepare deployment package
      run: |
        # Create deployment directory
        mkdir -p deployment
        
        # Copy the entire standalone output
        cp -R .next/standalone/* deployment/
        
        # Copy static files if they exist (they might be inside standalone already)
        if [ -d ".next/static" ]; then
          mkdir -p deployment/.next/static
          cp -R .next/static/* deployment/.next/static/
        fi
        
        # Copy public files if they exist
        if [ -d "public" ]; then
          mkdir -p deployment/public
          cp -R public/* deployment/public/
        fi
        
        # Create minimal package.json for Azure
        cat > deployment/package.json << 'EOF'
        {
          "name": "tasksystems-ng-production",
          "version": "1.0.0",
          "scripts": {
            "start": "node server.js"
          }
        }
        EOF
        
        # List deployment contents for verification
        echo "Deployment package contents:"
        find deployment -type f -name "*.js" -o -name "*.json" | head -10
        ls -la deployment/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: azure-app
        path: deployment/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: azure-app
        path: .

    - name: List deployed files for debugging
      run: |
        echo "Final deployment structure:"
        ls -la
        find . -name "server.js" -o -name "package.json" | xargs ls -la

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'task-site-ng'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}